<?php

namespace backend\controllers;

use Yii;
use common\models\Category;
use yii\web\Controller;
use yii\filters\VerbFilter;

/**
 * CategoryController implements the CRUD actions for Category model.
 */
class WechatController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'downlevel' => ['POST','GET'],
                    'uplevel' => ['POST','GET'],
                ],
            ],
        ];
    }



    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Creates a new Category model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionMenu()
    {
        return $this->render('menu');
    }

    public function actionMenuUpdate()
    {
        return $this->render('menu');
    }

}
